In [4]:
import pandas as pd

In [ ]:
# series = 1-dimensional
series = pd.Series(["BMW", "Toyota", "Honda", "Ford", "Chevrolet"])

In [4]:
series

0          BMW
1       Toyota
2        Honda
3         Ford
4    Chevrolet
dtype: object

In [ ]:
# series = 1-dimensional
colors = pd.Series(["Red", "Blue", "Green", "Black", "White"])
colors

0      Red
1     Blue
2    Green
3    Black
4    White
dtype: object

In [3]:
# DataFrame = 2-dimensional
car_data = pd.DataFrame({"Car make": series, "Color": colors})
car_data

NameError: name 'pd' is not defined

In [5]:
# Import data

car_sales = pd.read_csv("car-sales.csv")
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [ ]:
# Exporting a dataframe

car_sales.to_csv("exported-car-sales.csv", index=False)
car_sales.to_excel("exported-car-sales.xlsx", index=False)

In [6]:
# Attributes
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [ ]:
car_columns = car_sales.columns

'Make'

In [12]:
car_sales.index

RangeIndex(start=0, stop=10, step=1)

In [17]:
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [18]:
car_prices = pd.Series([30000, 15000, 20000, 25000, 18000])
car_prices.mean()

np.float64(21600.0)

In [19]:
car_sales.sum()

Make             ToyotaHondaToyotaBMWNissanToyotaHondaHondaToyo...
Colour               WhiteRedBlueBlackWhiteGreenBlueBlueWhiteWhite
Odometer (KM)                                               786014
Doors                                                           40
Price            $4,000.00$5,000.00$7,000.00$22,000.00$3,500.00...
dtype: object

In [20]:
car_sales['Doors'].sum()

np.int64(40)

In [21]:
len(car_sales)

10

In [23]:
## Viewing and selecting data

car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [24]:
car_sales.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [25]:
animals = pd.Series(["cat", "dog", "bird", "fish", "lizard"], index=[0, 3, 9, 8 , 3])
animals

0       cat
3       dog
9      bird
8      fish
3    lizard
dtype: object

In [26]:
animals.loc[3]

3       dog
3    lizard
dtype: object

In [28]:
car_sales.iloc[0:3]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
2  Toyota   Blue          32549      3  $7,000.00

In [29]:
car_sales[car_sales["Make"] == "Toyota"]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
2  Toyota   Blue          32549      3  $7,000.00
5  Toyota  Green          99213      4  $4,500.00
8  Toyota  White          60000      4  $6,250.00

In [ ]:
car_sales[car_sales["Make"].str.contains("Toyota")]
car_sales[car_sales["Odometer (KM)"] > 100000]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
4  Nissan  White         213095      4  $3,500.00